export const ADD_SERVICE = 'ADD_SERVICE';
export const REMOVE_SERVICE = 'REMOVE_SERVICE';
export const UPDATE_SERVICE = 'UPDATE_SERVICE';

export const CHANGE_SERVICE_FIELD = 'CHANGE_SERVICE_FIELD';
export const CLEAR_SERVICE_FIELD = 'CLEAR_SERVICE_FIELD';
export const CHANGE_MODE = 'CHANGE_MODE';
export const EDIT_FIELD = 'EDIT_FIELD';
